### ISSUE TITLE
Code available ?

### ISSUE THREAD

**Issue by Dinxin** [suzgunmirac/prompt-and-rerank#1]
3 months has passed .....

**Comment by suzgunmirac** [comment]
Hi @Dinxin, we are sorry for the delay. Because the paper is currently under review, we have been waiting to hear back from the conference before releasing the code. In light of this demand for our code, however, we will be sharing our code and datasets in the next few days. Please stay tuned.

**Comment by xszheng2020** [comment]
Hi, @suzgunmirac, thanks for your inspiring paper, may I ask whether the code would be released soon?

**Comment by suzgunmirac** [comment]
Please do pardon me for my belated response.

You can use the following Colab notebook to experiment with our Prompt-and-Rerank method: https://colab.research.google.com/drive/1kpO7-KHOv39_T58Oi0Z2fKsAJ6WXK0YY?usp=sharing.

We will also release our code and data very soon. Thanks for your patience.
